// import { GoogleConfig } from '../interface/google-config.interface';

export const twitchConfig = {
    clientID: 'wosxuqcw5xu0nxfulk3772lazafi1z',
    clientSecret: 'a6edruoptxvbsl9uot1lrbd6hy37uz',
    callbackURL: `http://localhost:3000/auth/twitch/callback`,
    scope: 'user:read:email', // user:read:email
    authorizationURL: 'https://id.twitch.tv/oauth2/authorize',
    tokenURL: 'https://id.twitch.tv/oauth2/token',
    response_type: 'code',
    grant_type: ' authorization_code',
    passReqToCallback: true,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  };